app/urls.py
from django.urls import path
from app import views
from .views import ContactView, ContactResultView, HistoryView

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('area/<str:area>/', views.IndexView.as_view(), name='index'),
    path('area/<str:attraction>/', views.IndexView.as_view(), name='index'),
    path('area/<str:area>/<str:category>/', views.IndexView.as_view(), name='index'),
    path('area/<str:area>/<str:attraction>/<str:category>/', views.IndexView.as_view(), name='index'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/preview/', views.PreviewPostView.as_view(), name='preview'),
    path('about', views.AboutView.as_view(), name='about_top'),
    path('category/<str:category>/', views.CategoryNameView.as_view(), name='category_name'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('like/', views.LikeView, name='like'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('contact/result/', ContactResultView.as_view(), name='contact_result'),
    path('histroy', HistoryView.as_view(), name='history'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.mail import BadHeaderError, message, send_mail
from django.http import HttpResponse
from .models import Area, Attraction, Category


class PostForm(forms.Form):
    # here

    title = forms.CharField(max_length=50, label='タイトル')
    # area = forms.ChoiceField(label='エリア', widget=forms.Select, choices=list(self.area_choice.items()), initial="----選択してください")
    area = forms.ModelChoiceField(queryset=Area.objects.all(), label='エリア', widget=forms.Select, initial="----選択してください")
    # attraction = forms.ChoiceField(label='アトラクション', widget=forms.Select, choices=list(self.attraction_choice.items()))
    attraction = forms.ModelChoiceField(queryset=Attraction.objects.all(), label='アトラクション', widget=forms.Select, initial="----エリアを選択してください")
    # category = forms.ChoiceField(label='カテゴリ', widget=forms.Select, choices=list(self.category_choice.items()), initial="----選択してください")
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label='カテゴリ', widget=forms.Select, initial="----選択してください")
    content = forms.CharField(label='内容', widget=forms.Textarea())
    image = forms.ImageField(label='イメージ画像', required=False)

    # def clean_name(self):
    #     area = self.cleaned_data.get('area')
    #     if area in ('ワールドバザール'):
    #         self.add_error('area', 'お名前に禁止ワードが含まれています')
    #     return area


CATEGORIES = (
    ('0', '----選択してください'),
    ('1', 'このサイトについて'),
    ('2', '投稿記事について'),
    ('3', '不具合について'),
    ('4', 'ご意見・ご要望'),
)

class ContactForm(forms.Form):
    name = forms.CharField(
        label='お名前',
        max_length=30, 
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '入力してください',
        })
    )
    email = forms.EmailField(
        label='Email',
        max_length=100,
        widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '入力してください',
        })
    )
    cntct_category = forms.ChoiceField(
        label='カテゴリー',
        choices=CATEGORIES,
        widget=forms.Select(attrs={
        'class': 'form-control',
        })
    )
    message = forms.CharField(
        label='お問い合わせ内容',
        max_length=5000,
        widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': '入力してください(最大5,000文字)',
        }),
    )
    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name in ('ばか', 'あほ', 'まぬけ', 'うんこ', '死ね'):
            self.add_error('name', 'お名前に禁止ワードが含まれています')
        return name

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if message in ('ばか', 'あほ', 'まぬけ', 'うんこ', '死ね'):
            self.add_error('message', 'お問い合わせ内容に禁止ワードが含まれています')
        return message

app/templates/app/about.html
{% extends "app/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

<div>
    <h2 class="ttl-bd mt-4 mb-4">DISNEY SIDE STORIES作成の目的</h2>
</div>
<div class="container">
    <div class="contents row">
        <div class="col-xs-12 col-lg-6">
            <p>　付き合いたての彼女を連れて訪れたディズニーランド。当時学生だった私は冷や汗をかいていました。</p>
            <p>　（会話が進まない・・・）</p>
            <p>　緊張のあまり話題が浮かばず、気まずさと焦りで重たい空気が漂い始めていました。</p>
            <p>　そんな中、ふと目に入った隠れミッキーを話したところ嬉しそうにはしゃぐ彼女。</p>
            <p>　一度深呼吸をしてから周りを見渡すと、建物のデザイン、色使い、細かなモニュメントや隠れミッキー等、パークの至る所にゲストを楽しませようとする工夫が散りばめられていることに気づきました。</p>
            <p>　そんな無数の工夫を拾い上げ、会話に盛り込むことで自然と彼女との雰囲気も和らぎ、パークを出ることにはサイドのディズニーデートを約束するほど堪能していたのでした。</p>
            
        </div>
        <div class="col-xs-12 col-lg-6 rounded">
            <img src="{% static 'img/aboutDSS.png' %}" alt="" class="img-fluid aboutDSS">
        </div>
    </div>
    <div class="contents row mt-5">
        <div class="ccol-xs-12 col-lg-6 rounded">
            <img src="{% static 'img/aboutDSS2.png' %}" alt="" class="img-fluid aboutDSS2">
        </div>
        <div class="col-xs-12 col-lg-6">
            <p>　夢と魔法の国。全世界のディズニーランドの設計を行うイマジニア社の想像力とホスピタリティが創り上げるのは、お城やアトラクション等のきらびやかな建造物だけではありません。</p>
            <p>　隠れミッキー等の簡単には気づけないような細部や、目には見えない時代背景等、これらを知ることで目に入るもの全てが魅力的に写り、園内での時間が更に楽しいものになるでしょう。</p>
            <p>　全てのディズニーランドファン、これからファンになる人々、冷や汗をかいていた当時の自分のため、ディズニーランドの奥深さや楽しさを最大限伝えることを目的としてこのファンサイトを立ち上げました。</p>
        </div>
    </div>
</div>
<hr class="about-border">
<div class="container mt-5">
    <div class="profile row">
        <div class="col-xs-12 col-lg-5">
            <img src="{% static 'img/minari.png' %}" alt="" class="img-thumbnail rounded-circle img-profile mx-auto d-block">
        </div>
        <div class="col-xs-12 col-lg-7">
            <h4>管理人：みなり</h4>
            <p>パーク訪問実績：東京ディズニーランド、東京ディズニーシー、香港ディズニーランド、ウォルトディズニーワールド、ディズニーランドパリ
                夢はクルーズ含め、全世界のディズニーランドをめぐること！
            </p>
        </div>
    </div>
    <br>
    <br>
    <br>
    <p class="about-p small">DISNEY SIDE STORIESは東京ディズニーリゾートにまつわる裏話やお得情報を共有・投稿するファンサイトです。<br>The Walt Disney Companyや株式会社オリエンタルランド等のディズニー関連会社とは一切関係ありません。</p>
</div>


    {% endblock %}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/DSS_favicon.png' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&family=Noto+Sans+JP&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/595ffca410.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <title>DSS ディズニー裏話情報サイト</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg border-bottom" style="padding:10px">
        <div class="container">
            <a class="navbar-b" href="/">
                <img src="{% static 'img/DSS_SiteLogo.png' %}" alt="">
                <p class="catch-copy my-0 py-0 mr-0">テストディズニーリゾートをもっと楽しむ！<br>ディズニーランド・シー裏話共有サイト</p>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold mx-xs-3 " href="/">
                            <i class="fas fa-list mr-2"></i>記事一覧 <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold mx-xs-3" href="{% url 'post_new' %}">
                            <i class="far fa-paper-plane mr-2"></i>投稿 </span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle font-weight-bold mx-xs-3" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user mr-2"></i>マイページ
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'mypost' %}">
                                <i class="fas fa-pen-fancy mr-2"></i>My 投稿記事
                            </a>
                            <a class="dropdown-item" href="{% url 'myfavorite' %}">
                                <i class="far fa-heart mr-2"></i>My お気に入り
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account_logout' %}">
                                <i class="fas fa-sign-out-alt mr-2"></i>ログアウト
                            </a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold mx-xs-3 " href="/">
                            <i class="fas fa-list mr-2"></i>記事一覧 <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold mx-xs-3" href="{% url 'account_login' %}">
                            <i class="fas fa-sign-in-alt mr-2"></i>ログイン 
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link font-weight-bold mx-xs-3" href="{% url 'account_signup' %}">
                            <i class="fas fa-user-plus mr-2"></i>新規登録 <span class="sr-only">(current)</span>
                        </a>
                    </li>
                {% endif %}
                </ul>
                <form class="form-inline my-2 my-lg-0 flex-flow-delete" action="{% url 'search' %}" method="get">
                    <input class="form-control-search mr-0" name="keyword" type="search" placeholder="キーワード検索" aria-label="Search">
                    <button class="btn btn-sch btn-secondary my-2 my-sm-0" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </nav>

    <main>
        <div class="container col-xl-el col-expand-lg">
            {% block content %}
            {% endblock %}

        </div>
    </main>

    <footer class="mt-3 py-2 footer border-top">
        <div class="container link">
            <a href="{% url 'about_top' %}" class="footer-link" >サイト概要</a>
            <a href="{% url 'contact' %}" class="footer-link">お問い合わせ</a>
            <a href="{% url 'history' %}" class="footer-link">更新履歴</a>
            <a rel="noopener" href="https://twitter.com/minari766"class="footer-link"><i class="fab fa-lg fa-twitter link-twitter"></i></a>
            <a rel="noopener" href="https://twitter.com/minari766"class="footer-link"><i class="fab fa-lg fa-instagram link-instagram"></i></a>
        </div>
        <p class="m-0 text-center footer-sign">2020 - 2021 みなり</p>
    </footer>

{% block extra_js %}
<script>
$(document).ready(function(){
    $(".search-wrapper input").mouseenter(function(){
        $(".search-wrapper button").css("background-color", "#4aba10");
    });
    $(".search-wrapper input").mouseout(function(){
        $(".search-wrapper button").css("background-color", "" );
    });
});
</script>
{% endblock %}

</body>

</html>

app/templates/app/contact.html
{% extends "app/base.html" %}
{% load widget_tweaks %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="ttl-bd mt-4 mb-4">お問い合わせ</h2>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-info">送信</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/contact_result.html
{% extends "app/base.html" %}

{% block content %}
<div class="m-4">
    {{ success }}
    <div class="m-4 text-right">
        <u class="" href="/">ホームへ戻る</u>
    </div>
</div>
{% endblock %}

app/templates/app/history.html
{% extends "app/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

<div>
    <h2 class="ttl-bd mt-4 mb-4">更新履歴</h2>
</div>
<div class="container">
    <h3 class="m-4">工事中</h3>
</div>


    {% endblock %}

app/templates/app/post_delete.html
{% extends "app/base.html" %}

{% block content %}
<h2 class="my-4">{{ post_data.title }}</h2>
<hr>
<h5 class="my-4">削除してもよろしいですか？</h5>
<form method="post">
    {% csrf_token %}
    <button class="btn btn-danger" type="submit">削除する</button>
</form>

{% endblock %}

app/templates/app/post_form.html
{% extends "app/base.html" %}
{% load widget_tweaks %}

{% block content %}

<div>
    <h2 class="ttl-bd mt-4 mb-4">投稿情報</h2>
</div>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="formpost">
        <div>タイトル<span>※必須</span></div>
        {% render_field form.title class="form-control" placeholder="タイトルを入力してください" %}
    </div>
    <div class="formpost">
        <div>エリア<span>※必須</span></div>
        {% render_field form.area class="form-control" placeholder="選択してください" %}
    </div>
    <div class="formpost">
        <div>アトラクション<span>※必須</span></div>
        {% render_field form.attraction class="form-control" placeholder="選択してください" %}
        {% for field in form %}
            {% for error in field.errors %}
                ※アトラクションを選択してください<br>
            {% endfor %}
        {% endfor %}
        {% for error in form.attraction.non_field_errors %} 
            ※{{ error }}
        {% endfor %}
    </div>
    <div class="formpost">
        <div>記事カテゴリ<span>※必須</span></div>
        {% render_field form.category class="form-control" placeholder="選択してください" %}
    </div>
    <div class="formpost">
        {{ form.image }}
    </div>
    <div class="formpost">
        <div>本文（最大10,000文字）<span>※必須</span></div>
        {% render_field form.content class="form-control" placeholder="" %}
    </div>
    <div class="text-center">
        <button class="btn btn-info" type="submit">投稿確認画面へ進む</button>
    </div>
</form>

{% endblock %}

{% block extra_js %}
    <script>
        const areaElement = $('#id_area');
        console.log("areaElement", areaElement)
        const attractionElement = $('#id_attraction');
        const area_attraction = {
            '----選択してください': [
                {
                    'value': '1',
                    'name': '----エリアを選択してください'
                },
            ],
            'ワールドバザール': [
                {
                    'value': '2',
                    'name': 'オムニバス'
                },
                {
                    'value': '3',
                    'name': 'ペニーアーケード'
                },
                {
                    'value': '4',
                    'name': 'ワールドバザール（その他）'
                },
            ],
            'アドベンチャーランド': [
                {
                    'value': '5',
                    'name': 'ウエスタンリバー鉄道'
                },
                {
                    'value': '6',
                    'name': 'カリブの海賊'
                },
                {
                    'value': '7',
                    'name': 'ジャングルクルーズ'
                },
                {
                    'value': '8',
                    'name': 'スイスファミリー・ツリーハウス'
                },
                {
                    'value': '9',
                    'name': '魅惑のチキルーム：スティッチ・プレゼンツ"アロハ・エ・コモ・マイ！"'
                },
                {
                    'value': '10',
                    'name': 'アドベンチャーランド（その他）'
                },
            ],
            'ウエスタンランド': [
                {
                    'value': '11',
                    'name': 'ウエスタンランド・シューティングギャラリー'
                },
                {
                    'value': '12',
                    'name': 'カントリーベア・シアター'
                },
                {
                    'value': '13',
                    'name': '蒸気船マークトウェイン号'
                },
                {
                    'value': '14',
                    'name': 'トムソーヤ島いかだ'
                },
                {
                    'value': '15',
                    'name': 'ビッグサンダー・マウンテン'
                },
                {
                    'value': '16',
                    'name': 'ウエスタンランド（その他）'
                },
            ],
            'クリッターカントリー': [
                {
                    'value': '17',
                    'name': 'スプラッシュ・マウンテン'
                },
                {
                    'value': '18',
                    'name': 'ビーバーブラザーズのカヌー探検'
                },
                {
                    'value': '19',
                    'name': 'クリッターカントリー（その他）'
                },
            ],
            'ファンタジーランド': [
                {
                    'value': '20',
                    'name': 'アリスのティーパーティー'
                },
                {
                    'value': '21',
                    'name': 'イッツ・ア・スモールワールド'
                },
                {
                    'value': '22',
                    'name': '白雪姫と七人のこびと'
                },
                {
                    'value': '23',
                    'name': 'シンデレラのフェアリーテイル・ホール'
                },
                {
                    'value': '24',
                    'name': '空飛ぶダンボ'
                },
                {
                    'value': '25',
                    'name': '美女と野獣"魔法のものがたり"'
                },
                {
                    'value': '26',
                    'name': 'ピーターパン空の旅'
                },
                {
                    'value': '27',
                    'name': 'ピノキオの冒険旅行'
                },
                {
                    'value': '28',
                    'name': 'プーさんのハニーハント'
                },
                {
                    'value': '29',
                    'name': 'ホーンテッドマンション'
                },
                {
                    'value': '30',
                    'name': 'ミッキーのフィルハーマジック'
                },
                {
                    'value': '31',
                    'name': 'キャッスルカルーセル'
                },
                {
                    'value': '32',
                    'name': 'ファンタジーランド（その他）'
                },
            ],
            'トゥーンタウン': [
                {
                    'value': '33',
                    'name': 'ガジェットのゴーコースター'
                },
                {
                    'value': '34',
                    'name': 'グーフィーのペイント&プレイハウス'
                },
                {
                    'value': '35',
                    'name': 'チップとデールのツリーハウス'
                },
                {
                    'value': '36',
                    'name': 'トゥーンパーク'
                },
                {
                    'value': '37',
                    'name': 'ドナルドのボート'
                },
                {
                    'value': '38',
                    'name': 'ミニーの家'
                },
                {
                    'value': '39',
                    'name': 'ロジャーラビットのカートゥーンスピン'
                },
                {
                    'value': '40',
                    'name': 'ミニーのスタイルスタジオ'
                },
                {
                    'value': '41',
                    'name': 'ミッキーの家とミート・ミッキー'
                },
                {
                    'value': '42',
                    'name': 'トゥーンタウン（その他）'
                },
            ],
            'トゥモローランド': [
                {
                    'value': '43',
                    'name': 'スター・ツアーズ：ザ・アドヴェンチャーズ・コンティニュー'
                },
                {
                    'value': '44',
                    'name': 'スティッチ・エンカウンター'
                },
                {
                    'value': '45',
                    'name': 'スペース・マウンテン'
                },
                {
                    'value': '46',
                    'name': 'バズ・ライトイヤーのアストロブラスター'
                },
                {
                    'value': '47',
                    'name': 'ベイマックスのハッピーライド'
                },
                {
                    'value': '48',
                    'name': 'モンスターズ・インク“ライド&ゴーシーク！”'
                },
                {
                    'value': '49',
                    'name': 'トゥモローランド（その他）'
                },
            ],
        };
        console.log("area_attraction", area_attraction)

    const changeArea = (select) => {
        attractionElement.children().remove();
        const parentId = $('#id_area option:selected').text();
        console.log("parentId", parentId)
        const categoryList = area_attraction[parentId];
        console.log("categoryList", categoryList)
        for (const category of categoryList) {
            console.log("category", category)
            const option = $('<option>');
                console.log("option", option)
                option.val(category['value']);
                option.text(category['name']);
                attractionElement.append(option);
            }
            if (select !== undefined) {
                attractionElement.val(select);
            }
        };
        
        $('#id_area').on('change', () => {
            changeArea();
        });

        if (areaElement.val()) {
            const selectedCategory = attractionElement.val();
            changeArea(selectedCategory);
        }
    </script>
{% endblock %}